---
title: "Lab 06 - Functions and iterations"
author: "Emily Gibson"
date: "`r Sys.Date()`"
output: html_document
---


### Packages and Data

```{r load-packages, message=FALSE}
library(tidyverse) 
library(ggplot2)
```

```{r diamon_rename}
diamonds <- diamonds %>% rename(
    depth_pct = depth,
    length_mm = x,
    width_mm = y,
    depth_mm = z,
    table_pct = table
  )
```


## Exercise 1

```{r}
# Do some preliminary investigations & cleaning

diamonds %>%
  filter(length_mm != 0 & width_mm != 0, depth_mm != 0) %>%
  summarise(mean_length = mean(length_mm), mean_depth = mean(depth_mm), mean_width = mean(width_mm))

diamonds %>%
  ggplot(mapping = aes(x = depth_pct, y = length_mm)) + geom_point()

diamonds %>%
  ggplot(mapping = aes(x = depth_pct, y = width_mm)) + geom_point()

diamonds %>%
  ggplot(mapping = aes(x = depth_pct, y = depth_mm)) + geom_point()

diamonds %>%
  group_by(clarity) %>%
  ggplot(mapping = aes(x = price, y = clarity)) + geom_boxplot()

diamonds %>%
  group_by(cut) %>%
  ggplot(mapping = aes(x = price, y = cut)) + geom_boxplot()

diamonds %>%
  group_by(cut) %>%
  ggplot(mapping = aes(x = clarity, y = carat, fill = cut)) + geom_col(position = "dodge")

```


## Exercise 2

```{r}

diamonds <- diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100)

# Overall table_mm arithmetic mean?

diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100) %>%
  summarise(mean = mean(table_mm))




# table_mm arithmetic mean within each clarity category

diamonds %>%
  mutate(table_mm = table_pct * width_mm / 100) %>%
  group_by(clarity) %>%
  summarise(mean_table = mean(table_mm))




```

The better ther clarity, the smaller the table percentage (percentage between width of the table and the diamonds overall width)

## Exercise 3

_Do derivation on paper, unless you know how to write LaTeX code_


## Exercise 4

```{r}
# Write gmean() command

gmean <- function(x) {
  exp(mean(log(x)))
}

```

## Exercise 5

```{r, error = TRUE}

test_data <- list(
  test1 = c(2.1, 3.8, 4.2),
  test2 = c(1, 10, 100, 1000),
  test3 = c(0, 1, 4),
  test4 = c(0.38,  0.94, -1.56),
  test5 = c(TRUE, TRUE),
  test6 = c("6", "7", "8")
)

# Create for loop to test gmean() on the above examples

  for (test in test_data){
    print(gmean(test))
  }

```


## Exercise 6

```{r}
# Copy gmean() from Ex4 and edit it to check the input




# Copy your code from Ex 5 to test your new command





```


## Exercise 7

```{r}
# Overall table_mm geometic mean?






# table_mm geometic mean within each clarity category






```

_Add your comment here_


## Exercise 8 (optional)

```{r}
# Create gmean2() that computes the geometric mean 
#   that uses the original definition






```


## Exercise 9 (optional)

```{r}
# Create a function that computes the harmonic mean







```
